[workspace]
resolver = "3"
members = ["coms", "server"]

[workspace.dependencies]
mc-coms = { path = "./coms" }
serde = { version = "1.0.228", features = ["derive"] }
tokio = { version = "1.47.1", features = ["io-util"] }
