[package]
name = "mc-server-rs"
version = "0.1.0"
edition = "2024"

[dependencies]
chrono = "0.4.42"
color-eyre = "0.6.5"
eyre = "0.6.12"
log = "0.4.28"
pretty_env_logger = "0.5.0"
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.145"
serde_with = "3.15.0"
thiserror = "2.0.17"
tokio = { version = "1.47.1", features = ["io-util"] }
uuid = { version = "1.18.1", features = ["serde"] }
