[package]
name = "mc-server-rs"
version = "0.1.0"
edition = "2024"

[dependencies]
chrono = "0.4.42"
log = "0.4.28"
pretty_env_logger = "0.5.0"
serde = { version = "1.0.228", features = ["derive"] }
thiserror = "2.0.17"
tokio = { version = "1.47.1", features = ["io-util"] }
uuid = "1.18.1"
